### ISSUE TITLE
Add SYSTEM-PATH

### ISSUE THREAD

**Issue by Lionhunt3r** [eichingertim/ProjectCreationAutomation#1]
How do I add python to my system-path correctly?

**Comment by eichingertim** [comment]
First of all, check if you have already added it correctly by typing python into your command-line and hit enter. If python opens you added it correctly. Otherwise, just follow these steps:
https://geek-university.com/python/add-python-to-the-windows-path/

**Comment by Lionhunt3r** [comment]
ok thats correct, but when I try to create a new Project it says create is not a command.

**Comment by eichingertim** [comment]
okay, you have to but the path of the create.bat file into the system-path, too. 
I just added a newer version of this project, where you don't need a web-driver like selenium.

**Comment by Lionhunt3r** [comment]
that means? what do i have to change now, when we dont need selenium anymore?

**Comment by eichingertim** [comment]
okay, so I think the easiest way to make it work, is to clone this project again to get the newer version and then go through all the steps in the README again (sorry for the effort).

**Comment by Lionhunt3r** [comment]
I mean, i commited also your changes in my script.py file, but it again says the command create is not existend or not spelled in the correct way

**Comment by eichingertim** [comment]
did you put the path of the create.bat file to your system path?
After that, you have to restart your command line. then the create-command should work.

**Comment by Lionhunt3r** [comment]
it works

**Comment by Lionhunt3r** [comment]
dont know why... i just reopened cmd and it works

**Comment by eichingertim** [comment]
okay, nice:) if you have any other issues just write a comment:)

**Comment by Lionhunt3r** [comment]
Note: When I created a new project, it says that a remote connection already exists. and there i see that the programm tries to go on your account. so I just added "git remote rm origin" before git add remote origin and then i dont get that problem.

**Comment by eichingertim** [comment]
Okay thank you

**Comment by Lionhunt3r** [comment]
but anyways its fked up... im going to get through that thing again.
